// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfmqcywzn_hdbFTMM81ZdQxpOF37vjZn8',
    appId: '1:614627181845:web:087f4589fa65cd64a4151c',
    messagingSenderId: '614627181845',
    projectId: 'todoapp-e58a5',
    authDomain: 'todoapp-e58a5.firebaseapp.com',
    storageBucket: 'todoapp-e58a5.firebasestorage.app',
    measurementId: 'G-Z834RLQFEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMBAe3kQmBTgAaCA83mkOlE5H7lvI8Cls',
    appId: '1:614627181845:android:4b91eb0f304b8a57a4151c',
    messagingSenderId: '614627181845',
    projectId: 'todoapp-e58a5',
    storageBucket: 'todoapp-e58a5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfmqcywzn_hdbFTMM81ZdQxpOF37vjZn8',
    appId: '1:614627181845:web:ecd4dd3feea4b49ea4151c',
    messagingSenderId: '614627181845',
    projectId: 'todoapp-e58a5',
    authDomain: 'todoapp-e58a5.firebaseapp.com',
    storageBucket: 'todoapp-e58a5.firebasestorage.app',
    measurementId: 'G-K1QWSSV30W',
  );

}